### ISSUE TITLE
Vite 4 Support

### ISSUE THREAD

**Issue by TheGlenn88** [clinggroup/vite-plugin-rollbar#1]
Are we able to provide support for Vite 4?

I can't see a reason why this wouldn't work already by updating the dependency version.

**Comment by rang-ali** [comment]
Sorry for the delay. This is now fixed in [v0.0.13](https://github.com/clinggroup/vite-plugin-rollbar/commit/6d1a06593870f6c17729466091c200feb09efdff#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R54)
