### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by walkingbrad** [clinggroup/vite-plugin-rollbar#3]
I am using Typescript `4.9.4` and get the below error immediately when I run the vite build.

My `package.json` has:
```
type: "module"
```

My `tsconfig.json` has:
```
"allowSyntheticDefaultImports": true,
"esModuleInterop": true,
```

Error:
```
failed to load config from 
/my/frontend/repo/vite.config.js
error when starting dev server:
/my/frontend/repo/node_modules/vite-plugin-rollbar/esm/index.js:1
import FormData from 'form-data';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at ModuleWrap.<anonymous>
(node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by rang-ali** [comment]
Can you try adding `"module": "es2020"` inside your tsconfig.json file?

**Comment by walkingbrad** [comment]
I've stepped away from this tool for now, but if I end up trying it out again I'll come back and report. Feel free to close if you want.

**Comment by marshallds** [comment]
I also ran into this problem. Looks like a change to package.json fixes it. I've PR'd that change: #5

**Comment by mrth2** [comment]
+1, I added `type:module` to `packpage.json` & `module:es2020` to `tsconfig` but still not be able to sync the source map
err: FormData is not defined.
detail:
![image](https://github.com/clinggroup/vite-plugin-rollbar/assets/8658653/4b25b504-fc28-4ed4-818d-8de90b0c7cf7)

**Comment by rang-ali** [comment]
> +1, I added `type:module` to `packpage.json` & `module:es2020` to `tsconfig` but still not be able to sync the source map err: FormData is not defined. detail: ![image](https://user-images.githubusercontent.com/8658653/277340677-4b25b504-fc28-4ed4-818d-8de90b0c7cf7.png)

@mrth2 are you running node v18+?

**Comment by mrth2** [comment]
@rang-ali  nope, it's node v16.14.2
